# Header Menu
menu:
  Home: /
  Archives: /archives
  音乐: /2017/06/04/music
  # change github and email values to your own addresses
  Github: https://github.com/yaomaocai
  联系邮箱: mailto:799787222@qq.com
  关于: /2017/06/04/about
  公益: /archives
rss: /atom.xml
avatar : http://a3.qpic.cn/psb?/V10qNYf00TX7C0/fpn1uKDqJxa6PMBZUtHzjsaMl.Rl1JfP*KCYN6J*XhA!/b/dIjB5MWDGwAA&bo=gAJVA7AHQAoBCgQ!&rf=viewer_4

# Set to false to disable banner
use_header_cover: true

# URL of the banner image
# Put your custom banner image under
# the theme's img folder: your-blog/themes/minimal-dual/source/img/
# and modify index_cover's value like so:
# index_cover: /img/your-custom-banner.jpg
# or
# Put your custom banner image under
# your blog's images folder: your-blog/source/images/
# and modify index_cover's value like so:
# index_cover: /images/your-custom-banner.jpg
# or
# Specify an online resource like so:
# index_cover: http://somewhere.com/path/to/banner.jpg
index_cover: /img/default-banner-dark.jpg

widgets:
- category
- tag
- archive

# widget behavior
archive_type: 'monthly'
show_count: true

# favicon
favicon: /favicon.png

# Google Analytics Tracking ID
google_analytics:

